### ISSUE TITLE
Change from https to ssh on prod

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/bcsr#36]
**[Original report](https://bitbucket.org/laborstudents/bcsr-flask/issue/36) by Guillermo ramos (Bitbucket: [guillermo_ramos](https://bitbucket.org/guillermo_ramos), GitHub: [memo330179](https://github.com/memo330179)).**

----------------------------------------

It is inconvenient to change the https URL every time a new member wants to use git

**Comment by sheggen** [comment]
Github solved this for us years ago.
