### ISSUE TITLE
Connie Lamb

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/bcsr#43]
**[Original report](https://bitbucket.org/laborstudents/bcsr-flask/issue/43) by Cody Myers (Bitbucket: [cody_myers](https://bitbucket.org/cody_myers), GitHub: [myersCody](https://github.com/myersCody)).**

----------------------------------------

Connie Lamb is having issues with uploading syllabi.

**Comment by sheggen** [comment]
7 years, probably not an issue anymore. No new reports from Connie
