### ISSUE TITLE
Some prefixes are not tied to the right Programs on import of data from spreadsheet

### ISSUE THREAD

**Issue by bryantal** [BCStudentSoftwareDevTeam/bcsr#60]
**[Original report](https://bitbucket.org/laborstudents/bcsr-flask/issue/60) by Scott Heggen (Bitbucket: [sheggen](https://bitbucket.org/sheggen), GitHub: [sheggen](https://github.com/sheggen)).**

----------------------------------------

When the file addNewTerm.py is run, it imports all data from a spreadsheet. Part of that process is createPrefixMapping\(\) which generates a dictionary of prefix-to-program mappings. Some prefixes belong to programs that don't match: the Latin \(LAT\) prefix is part of the Foreign Languages program. What currently happens is the script uses the last Program it had when it couldn't find a match. We got lucky with a number of them, like foreign languages, because they were always clumped together. Wellness \(WEL\) is going under Theatre now though, which is wrong \(Should be under Health and Human Performance\). 

We need to modify the addNewTerm.py script to handle these weird cases where a program has multiple prefixes under them. Ones I know we need to think about: Music \(MUS and MUA\), Foreign Languages \(LAT, SPN, FRN, CHN, etc.\), Health & Human Performance \(HHP and WEL\). There’s probably one or two more…

**Comment by sheggen** [comment]
@BrianRamsay was this what we were talking about, and is fixed now??

**Comment by BrianRamsay** [comment]
Pretty sure this issue was fixed by generating the prefix mapping from the existing courses in the database (which resolved a separate problem). Closing.
