### ISSUE TITLE
Buttons to expand Divisions and Departments should be on the left, not the right

### ISSUE THREAD

**Issue by BrianRamsay** [BCStudentSoftwareDevTeam/bcsr#75]
Buttons to expand Divisions and Departments should be on the left, not the right. https://bcsr.berea.edu/courses

**Comment by BrianRamsay** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix BCSR buttons](https://trello.com/c/RgpzVfY3/710-fix-bcsr-buttons)

**Comment by njounkengdaizem** [comment]
working on this

**Comment by AndersonStettner** [comment]
Brian fixed the buttons on Production.
